# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 673262c2cd6163eb766217ba38612fc648100e20ea83cc1dd3a763d3df89744f6a305f91e8d1acc4a8a178b89d92766e87195ef7155c2cc009b3e6a0b3c8445b

test:
  secret_key_base: f9ae7665add51652d3a0f398dfdc2bf8c6ebe87a26017fa2df5c906d491e244f23c165e717d60ae72688225780eebc0cd49c8f4b3eab826dccd5a10e23244762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
